# 변경 시 사이트 동작에 오류가 있을 수 있는 설정:
# 1. baseurl: 잘못 설정하면 리소스 로딩에 문제가 생길 수 있습니다.
# 2. url: 잘못 설정하면 절대 경로 기반의 링크가 깨질 수 있습니다.
# 3. card.image: 유효하지 않은 URL을 입력하면 이미지 로딩에 실패할 수 있습니다.
# 4. display 설정들: 모두 false로 설정하면 카드에 표시할 정보가 없어 의도치 않은 레이아웃이 될 수 있습니다.

# Card settings
card:
  # 디지털 명함에 표시될 이름입니다.
  name: 홍길동
  
  # 직함이나 직책을 나타냅니다.
  title: 소프트웨어 엔지니어
  
  # 연락 가능한 이메일 주소입니다.
  email: hong@example.com
  
  # 연락 가능한 전화번호입니다.
  phone: 010-1234-5678
  
  # 소속 회사나 조직명입니다.
  company: 테크 주식회사
  
  # 프로필 이미지의 URL입니다. 개인 식별이 가능한 이미지를 사용해야 합니다.
  image: https://picsum.photos/200

# Display settings
display:
  # 이름 표시 여부를 설정합니다. (true: 표시, false: 숨김)
  name: true
  
  # 직함 표시 여부를 설정합니다.
  title: true
  
  # 이메일 주소 표시 여부를 설정합니다.
  email: true
  
  # 전화번호 표시 여부를 설정합니다.
  phone: true
  
  # 회사명 표시 여부를 설정합니다.
  company: true

# Do not Touch !!!
# Site settings
title: 모두의오늘 온라인 명함
baseurl: ""
url: ""
